version: '3.9'

services:
  db:
    image: postgres:15
    container_name: ecommerce_db
    environment:
      POSTGRES_USER: yourusername    # Change to your desired PostgreSQL username
      POSTGRES_PASSWORD: yourpassword # Change to your desired PostgreSQL password
      POSTGRES_DB: ecommerce         # Name of the PostgreSQL database
    ports:
      - '5432:5432'  # Expose PostgreSQL on the default port
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist database data locally
    networks:
      - dev_network

# Define the network for PostgreSQL service
networks:
  dev_network:
    driver: bridge

# Define the named volume for PostgreSQL data persistence
volumes:
  pgdata:
